name: bio_env
dependencies:
  - nomkl
  - python=3.7
  - pip
  - conda-forge::rdkit
  - pip:
    - flask
    - dgllife==0.2.1
    - gunicorn==20.0.4
    - https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
    - dgl==0.4.3
